// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StartinhsMart.CoreService.EntityFrameworkCore;
using Volo.Abp.EntityFrameworkCore;

#nullable disable

namespace StartinhsMart.CoreService.Migrations
{
    [DbContext(typeof(CoreServiceDbContext))]
    [Migration("20260204120000_ChangePetCategoryToGuid")]
    partial class ChangePetCategoryToGuid
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("_Abp_DatabaseProvider", EfCoreDatabaseProvider.PostgreSql)
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StartinhsMart.CoreService.Pets.Pet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<float?>("Age")
                        .HasColumnType("real")
                        .HasColumnName("Age");

                    b.Property<string>("Breed")
                        .HasColumnType("text")
                        .HasColumnName("Breed");

                    b.Property<string>("Color")
                        .HasColumnType("text")
                        .HasColumnName("Color");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("CreationTime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("CreatorId");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("Description");

                    b.Property<string>("Gender")
                        .HasColumnType("text")
                        .HasColumnName("Gender");

                    b.Property<string>("HealthStatus")
                        .HasColumnType("text")
                        .HasColumnName("HealthStatus");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("uuid")
                        .HasColumnName("ImageId");

                    b.Property<bool>("IsBooth")
                        .HasColumnType("boolean")
                        .HasColumnName("IsBooth");

                    b.Property<bool>("IsStock")
                        .HasColumnType("boolean")
                        .HasColumnName("IsStock");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("LastModificationTime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("LastModifierId");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("Name");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("Price");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("Quantity");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.Property<int?>("Vaccinations")
                        .HasColumnType("integer")
                        .HasColumnName("Vaccinations");

                    b.Property<float?>("Weight")
                        .HasColumnType("real")
                        .HasColumnName("Weight");

                    b.HasKey("Id");

                    b.ToTable("AppPets", (string)null);
                });

#pragma warning restore 612, 618
        }
    }
}
