<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>StartinhsMart.CoreService</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\StartinhsMart.CoreService.Domain\StartinhsMart.CoreService.Domain.csproj" />
    <ProjectReference Include="..\StartinhsMart.CoreService.Application.Contracts\StartinhsMart.CoreService.Application.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.PermissionManagement.Application" Version="9.0.4" />
    <PackageReference Include="Volo.Abp.FeatureManagement.Application" Version="9.0.4" />
    <PackageReference Include="Volo.Abp.SettingManagement.Application" Version="9.0.4" />
    <PackageReference Include="Volo.Abp.Account.Pro.Public.Application" Version="9.0.4" />
    <PackageReference Include="Volo.Abp.Account.Pro.Admin.Application" Version="9.0.4" />
    <PackageReference Include="Volo.Abp.Identity.Pro.Application" Version="9.0.4" />
    <PackageReference Include="Volo.Saas.Host.Application" Version="9.0.4" />
  </ItemGroup>

</Project>
